# Version 1.0 - Initial release

version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /etc/seedbox/deluge:/config
      - /opt/seedbox/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_CLEANUP="true"
      - TZ="Europe/paris"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /etc/seedbox/jellyfin:/config
      - /opt/seedbox/media/:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /etc/seedbox/radarr:/config
      - /opt/seedbox/media/Films:/Films #optional
      - /opt/seedbox/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /etc/seedbox/sonarr:/config
      - /opt/seedbox/media/Series:/Series #optional
      - /opt/seedbox/downloads:/downloads #optional
    ports:
      -  8989:8989
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /etc/seedbox/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
